### ISSUE TITLE
Separate word counts for main text, references, appendix

### ISSUE THREAD

**Issue by fschaffner** [andrewheiss/quarto-wordcount#2]
Hi @andrewheiss,

Thanks for writing this extension!

In Quarto, it is possible to specify where the references should be included with `::: {#refs} :::` and to write an Appendix after the references, like this:

```
# Main text

Main text.

# References 

::: {#refs}
:::

# Appendix

Appendix text.
```

I was wondering if it would be possible to produce separate word counts for the main text (i.e., text before `::: {#refs} :::`) and text in the Appendix (i.e., text after `::: {#refs} :::`)? Perhaps this could be included in the output, like this:

```
300 total words
-------------------------------
100 words in text body
100 words in reference section
100 words in appendix
```

Thanks for considering this!

**Comment by andrewheiss** [comment]
Yeah, I need to figure this out some time :)

I've been playing with different ways of handling appendices with Quarto (see this discussion here for a few different options, like an appendix in one document or an appendix as a chapter in a book: https://github.com/quarto-dev/quarto-cli/discussions/4581). 

In a single document, I *think* Lua can extract anything in the `.appendix` class that gets generated when you use `{.appendix}`, but I'm not that proficient in Lua 😬

With a separate "chapter", it would require some way to handle multi-file documents, like in https://github.com/andrewheiss/quarto-wordcount/issues/1

**Comment by andrewheiss** [comment]
Phew, k, so I played with this a little and it seemed like a straightforward addition. It's easy enough to copy the approach from the reference extraction, with these functions for detecting the appendix div:

```lua
local appendix_words = 0

function is_appendix_div (blk)
   return (blk.t == "Div" and blk.identifier == "appendix")
end

function get_appendix (blks)
  local out = {}
   for _, b in pairs(blks) do
      if is_appendix_div(b) then
	      table.insert(out, b)
      end
   end
   return out
end

function remove_appendix (blks)
   local out = {}
   for _, b in pairs(blks) do
      if not (is_appendix_div(b)) then
	      table.insert(out, b)
      end
   end
   return out
end
```

…and this code for doing the actual extraction and printing:

```lua
local untabled = remove_all_tables_images(el.blocks)

  refs_title = el.meta["reference-section-title"]
  local unreffed = remove_all_refs(untabled)
  local unappendixed = remove_appendix(unreffed)
  pandoc.walk_block(pandoc.Div(unappendixed), body_count)
  local body_words_out = body_words .. " words in text body"
  
  local refs = get_all_refs(untabled)
  pandoc.walk_block(pandoc.Div(refs), ref_count)
  local ref_words_out = ref_words .. " words in reference section"
  
  local appendix = get_appendix(untabled)
  pandoc.walk_block(pandoc.Div(appendix), appendix_count)
  local appendix_words_out = appendix_words .. " words in appendix section"
  
  local total_words_out = body_words + ref_words + appendix_words .. " total words"
  
  local longest_out = math.max(string.len(body_words_out), 
                               string.len(ref_words_out), 
                               string.len(appendix_words_out), 
                               string.len(total_words_out))
  
  print(total_words_out)
  print(string.rep("-", longest_out))
  print(body_words_out)
  print(ref_words_out)
  print(appendix_words_out)
  print()
```

However, it keeps giving output like this:

```text
7117 total words
------------------------------
6360 words in text body
757 words in reference section
0 words in appendix section
```


I stuck some `print()` statements in `is_appendix_div()` to see what was going on:

```lua
function is_appendix_div (blk)
   print(blk.t)
   print(blk.identifier)
   print(" ")
   return (blk.t == "Div" and blk.identifier == "appendix")
end
```

…and it turns out that pandoc doesn't consider the appendix div to be a div; instead it's a heading:

```text
Header
appendix
```

I'm not sure how to target and extract the appendix div. In theory it should be a `div` or a `section`—at least that's how it appears in the rendered HTML:

![image](https://user-images.githubusercontent.com/73663/233273498-7ae8ce03-6445-4727-9562-a068ed12d60a.png)

But it doesn't seem like pandoc/Lua sees it as a div :(

**Comment by andrewheiss** [comment]
@fschaffner I just added some preliminary support for this (finally!). The main issue is that Quarto does some fancy behind-the-scenes work to generate an appendix section, and that happens after the word counting script (and I can't figure out how to make the word counting happen after the appendix generation). This is probably related to https://github.com/quarto-dev/quarto-cli/issues/4113

So as a workaround, you can stick all the appendix content in a special div with the id `appendix-count`:

```markdown
# Main text

Main text.

# References 

::: {#refs}
:::

::: {#appendix-count}
# Appendix

Appendix text.
:::
```

The script will then count everything in `#appendix-count` separately and give this output:

```
108 in the main text + references, with 23 in the appendix
----------------------------------------------------------
80 words in text body
28 words in reference section
23 words in appendix section
```

**Comment by andrewheiss** [comment]
Importantly, this doesn't properly count text when you use Quarto's `{.appendix}` feature to move stuff to the end. Anything you want counted as part of the appendix has to appear in the `#appendix-count` div.


```
# Main text

Main text.

# Some section {.appendix}

This will go in the appendix when rendering, but it will be counted as body text

# References 

::: {#refs}
:::

::: {#appendix-count}
# Appendix

Appendix text.
:::
```
