### ISSUE TITLE
Word count excluding code

### ISSUE THREAD

**Issue by Shelmith-Kariuki** [andrewheiss/quarto-wordcount#4]
Hi @andrewheiss , 

Thank you so much for this extension. I would want to know the word count, excluding code. 
Which part of the block of code below should I edit? 

`
body_count = {
  Str = function(el)
    -- we don't count a word if it's entirely punctuation:
    if el.text:match("%P") then
      body_words = body_words + 1
    end
  end,

  Code = function(el)
    _,n = el.text:gsub("%S+","")
    body_words = body_words + n
  end,

  CodeBlock = function(el)
    _,n = el.text:gsub("%S+","")
    body_words = body_words + n
  end
}

`

**Comment by andrewheiss** [comment]
This is fixed now with https://github.com/andrewheiss/quarto-wordcount/commit/f8cf097a1a6b612411688f776222d93166d8dccb

````qmd
---
title: "Code counting"
format: 
  wordcount-html:
    count-code-blocks: false
---

This sentence has seven words in it.

```{{r}}
# Here is some code

numbers <- 1:10
mean(numbers)
```
````

…which makes these counts:

```text
Overall totals:
----------------------------
- 7 total words
- 7 words in body and notes

Section totals:
----------------------------
- 7 words in text body
```
